# Read the Docs config file

version: 2

# Python config
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt

# Build docs in the docs/ directory using Sphinx
sphinx:
  configuration: docs/conf.py

# Which file formats to build
formats: all
